global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
        labels:
          group: 'prometheus'
  - job_name: node
    static_configs:
    - targets: ['host.docker.internal:9100']
  - job_name: 'kafka'
    static_configs:
    - targets: ['kafka:7071']