global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090','127.0.0.1:9091']
        labels:
          group: 'prometheus'
  - job_name: node
    static_configs:
    - targets: ['host.docker.internal:9100']