version: "3.9"
services:
  prometheus:
    image: quay.io/prometheus/prometheus:v2.26.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    depends_on:
      - node-exporter

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"